name: Test
on:
  # Ensure GitHub actions are not run twice for same commits
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
      - '!release-please--**'
  merge_group:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-2025]
        node-version: ['22']
      fail-fast: false
    steps:
      # Increasing the maximum number of open files. See:
      # https://github.com/actions/virtual-environments/issues/268
      - name: Increase open file limit
        run: sudo ulimit -Sn 65536
        if: "${{ matrix.os == 'macOS-latest' }}"
      - run: git config --global core.symlinks true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.2.4
      - name: Setup Deno dependencies
        run: deno cache https://deno.land/x/eszip@v0.55.2/eszip.ts
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Build
        run: npm run build --workspaces=true
      - name: Tests
        run: npm run test --workspaces=true
  test-node18:
    name: Test Node.js 18 for specific packages
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-2025]
      fail-fast: false
    steps:
      - run: git config --global core.symlinks true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node.js 18.14.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.0
          cache: 'npm'
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.2.4
      - name: Setup Deno dependencies
        run: deno cache https://deno.land/x/eszip@v0.55.2/eszip.ts
      - name: Install dependencies
        run: npm ci
      - name: Build
        # NOTE: These are run in the specified order, so they must be in topological order
        run: >-
          npm run build -w ./packages/types -w ./packages/dev-utils -w ./packages/runtime-utils -w ./packages/blobs -w
          ./packages/edge-functions -w ./packages/functions
      - name: Tests
        run: >-
          npm run test -w ./packages/types -w ./packages/dev-utils -w ./packages/runtime-utils -w ./packages/blobs -w
          ./packages/edge-functions -w ./packages/functions
